# This file is autogenerated from update.sh in the parent directory.
{
  dev = {
    version = "48.0.2564.10";
    sha256 = "1l13yp0ag6wa3vd4msw59cv3m9jkj8yfav9zqfl34v6l95fxf0hr";
    sha256bin32 = "1dp4dzjxmmi37vdjg7fgfq5rmnrr5f7fhmj36hn5xap6910wgwj4";
    sha256bin64 = "0fchia7fs19cgihbvf5xjgn7a3i69ldkbkrlhq4ajikpd0g3vkbn";
  };
  beta = {
    version = "47.0.2526.69";
    sha256 = "1higaf61nfygjcdsjjnqrwl02ajlc8manqk1qr3rz14631h7ya6p";
    sha256bin32 = "1ycpp41kp3vgf04l34nqw5ifjdjjrsyc6y9clrk6wqid44yfkaww";
    sha256bin64 = "01gvbni22kchwy4pkz2ika2qvfm075dbznqg5qcgv81yc4c4krjf";
  };
  stable = {
    version = "46.0.2490.86";
    sha256 = "14hxglm466qyfdzsi4gda9abaw6psz0byw67lvl5iy8gr25d467f";
    sha256bin32 = "0v81hfrciqijcz6vhwa3mcnq858mv4zxfvzk6p90hrcpmx4dbs68";
    sha256bin64 = "1b2m6i7g364raygckhy5dmvr96dsihdy6747ln6ah988ckz39i19";
  };
}
