# This file is autogenerated from update.sh in the parent directory.
{
  dev = {
    version = "48.0.2535.0";
    sha256 = "160iidgn5gi9jbdp7hazhdvk7p9bk7k721yifh9nb61r370ih105";
    sha256bin32 = "1fc3hd0f4qrccjklbahxarhn1dyaavadhygv6x0rgjc2cjxiij1b";
    sha256bin64 = "1xdmp7ss518bmv78nmhbbz12gh0s28ww0m4pxp6glbv5452w21x1";
  };
  beta = {
    version = "47.0.2526.16";
    sha256 = "01sa4x9s8ypcvkj6vi15619gxk9p30gcjqw68fzbbxw0lcnqk1y8";
    sha256bin32 = "0any688s5v2ra6ml21rqa4kpx9a7p6p6lms78w5mnvis86c7pzm5";
    sha256bin64 = "1nxqfgc06mpikrcg6cllcp8zgh3x88qj64fspm3rp4lwhj7qmxhl";
  };
  stable = {
    version = "46.0.2490.71";
    sha256 = "1dnwhwvn39x8lm1jszjn8y7vy478zy75gm696rr2dvk4kqj1hjyd";
    sha256bin32 = "1v1acg32dzmkydzy7sh6xjbzqar052iw8x8hql2yjz5kxznir4sf";
    sha256bin64 = "15ladhxiym760mid5zq09vp73irzwlp31br9yqslzgv4460ma3np";
  };
}
